name: Build Skia

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
          export PATH="${PWD}/depot_tools:${PATH}"
          git clone https://github.com/google/skia.git --branch chrome/m121 --single-branch
          cd skia
          bin/fetch-ninja
          python tools/git-sync-deps
          bin/gn gen out/release --args=" \
            is_debug=false \
            is_official_build=true \
            is_component_build=true \
            skia_use_system_expat=false \
            skia_use_system_libjpeg_turbo=false \
            skia_use_system_libpng=false \
            skia_use_system_libwebp=false \
            skia_use_system_zlib=false \
            skia_use_system_icu=false \
            skia_use_system_harfbuzz=false \
            skia_enable_android_utils=false \
            skia_enable_spirv_validation=false \
            skia_enable_tools=false \
            skia_enable_gpu_debug_layers=false \
            skia_use_jpeg_gainmaps=false \
            skia_use_libheif=false \
            skia_use_lua=false \
            skia_use_gl=false \
            skia_use_webgl=false \
            skia_use_direct3d=false \
            skia_gl_standard=\"\" \
            skia_enable_gpu=false"
          ninja -C out/release skia
        shell: bash  

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Package
          path: |
            skia/out/release/
          
