name: Install windows sdk

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Windows
        if: matrix.environment == 'windows-latest'
        run: |
          ls "C:\\Program Files (x86)\\Windows Kits\\10\\Lib"
        shell: bash   
