name: Build Skia

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Windows
        if: matrix.environment == 'windows-latest'
        run: |
          choco install windows-sdk-10.1 --confirm
          ls C:\Program Files (x86)\Windows Kits\10\Include
        shell: bash   
